@extends('layouts.app')
@section('styles')
<style type="text/css">
  body {
    padding-top: 66px  !important;
  }
</style>
@endsection
@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="p-4" style="">
        <div class="p-5 text-white" style="border-radius: 15px; background-color: #a1276d !important;">
          <div class="c13 doc-content">
            <h1>Terms of Use</h1>
            <p class="c2 title" id="h.gjdgxs"><span class="c12">Interpretation and Definitions</span></p>
            <h2 class="c10"><span class="c6">Interpretation</span></h2>
            <p class="c1">
                <span class="c0">
                    The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </span>
            </p>
            <h2 class="c10"><span class="c6">Definitions</span></h2>
            <p class="c1"><span class="c0">For the purposes of this Privacy Policy:</span></p>
            <p class="c4"><span class="c5">Account</span><span class="c0">&nbsp;means a unique account created for You to access our Service or parts of our Service.</span></p>
            <p class="c4"><span class="c5">Company</span><span class="c0">&nbsp;(referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Nursing WebPal.</span></p>
            <p class="c4">
                <span class="c5">Cookies</span>
                <span class="c0">&nbsp;are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</span>
            </p>
            <p class="c4"><span class="c5">Country</span><span class="c0">&nbsp;refers to: Philippines</span></p>
            <p class="c4"><span class="c5">Device</span><span class="c0">&nbsp;means any device that can access the Service such as a computer, a cellphone or a digital tablet.</span></p>
            <p class="c4"><span class="c5">Personal Data</span><span class="c0">&nbsp;is any information that relates to an identified or identifiable individual.</span></p>
            <p class="c4"><span class="c5">Service</span><span class="c0">&nbsp;refers to the Website.</span></p>
            <p class="c4">
                <span class="c5">Service Provider</span>
                <span class="c0">
                    &nbsp;means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf
                    of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
                </span>
            </p>
            <p class="c4">
                <span class="c5">Usage Data</span>
                <span class="c0">&nbsp;refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</span>
            </p>
            <p class="c4">
                <span class="c5">Website</span><span class="c0">&nbsp;refers to Nursing WebPal, accessible from </span>
                <span class="c0"><a class="c7" href="https://www.google.com/url?q=http://nursingwebpal.web&amp;sa=D&amp;source=editors&amp;ust=1672717699646676&amp;usg=AOvVaw04Ljq47dsbMZ9vPOc0dfJk">nursingwebpal.web</a></span>
            </p>
            <p class="c1 c14">
                <span class="c5">You</span>
                <span class="c0">&nbsp;means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</span>
            </p>
            <p class="c2 title"><span class="c12">Collecting and Using Your Personal Data</span></p>
            <h2 class="c10"><span class="c6">Types of Data Collected</span></h2>
            <h3 class="c10"><span class="c9">Personal Data</span></h3>
            <p class="c1">
                <span class="c0">
                    While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                </span>
            </p>
            <p class="c4"><span class="c0">Email address</span></p>
            <p class="c4"><span class="c0">First name and last name</span></p>
            <p class="c4"><span class="c0">Phone number</span></p>
            <p class="c4"><span class="c0">Address, State, Province, ZIP/Postal code, City</span></p>
            <p class="c1 c14"><span class="c0">Usage Data</span></p>
            <h3 class="c10"><span class="c9">Usage Data</span></h3>
            <p class="c1"><span class="c0">Usage Data is collected automatically when using the Service.</span></p>
            <p class="c1">
                <span class="c0">
                    Usage Data may include information such as Your Device&#39;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time
                    spent on those pages, unique device identifiers and other diagnostic data.
                </span>
            </p>
            <p class="c1">
                <span class="c0">
                    When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of
                    Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                </span>
            </p>
            <p class="c1"><span class="c0">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</span></p>
            <h3 class="c10"><span class="c9">Tracking Technologies and Cookies</span></h3>
            <p class="c1">
                <span class="c0">
                    We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve
                    and analyze Our Service. The technologies We use may include:
                </span>
            </p>
            <ul class="c3 lst-kix_list_1-0 start">
                <li class="c11 c8 li-bullet-0">
                    <span class="c5">Cookies or Browser Cookies.</span>
                    <span class="c0">
                        &nbsp;A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some
                        parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
                    </span>
                </li>
                <li class="c1 c8 li-bullet-0">
                    <span class="c5">Web Beacons.</span>
                    <span class="c0">
                        &nbsp;Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to
                        count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).
                    </span>
                </li>
            </ul>
            <p class="c1">
                <span>
                    Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web
                    browser. You can learn more about cookies on
                </span>
                <span>
                    <a class="c7" href="https://www.google.com/url?q=https://www.termsfeed.com/blog/cookies/%23What_Are_Cookies&amp;sa=D&amp;source=editors&amp;ust=1672717699648564&amp;usg=AOvVaw27Bi4fQaPaZ4feQk0UjX3m">TermsFeed website</a>
                </span>
                <span class="c0">&nbsp;article.</span>
            </p>
            <p class="c1"><span class="c0">We use both Session and Persistent Cookies for the purposes set out below:</span></p>
            <p class="c4"><span class="c5">Necessary / Essential Cookies</span></p>
            <p class="c4"><span class="c0">Type: Session Cookies</span></p>
            <p class="c4"><span class="c0">Administered by: Us</span></p>
            <p class="c4">
                <span class="c0">
                    Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.
                    Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
                </span>
            </p>
            <p class="c4"><span class="c5">Cookies Policy / Notice Acceptance Cookies</span></p>
            <p class="c4"><span class="c0">Type: Persistent Cookies</span></p>
            <p class="c4"><span class="c0">Administered by: Us</span></p>
            <p class="c4"><span class="c0">Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</span></p>
            <p class="c4"><span class="c5">Functionality Cookies</span></p>
            <p class="c4"><span class="c0">Type: Persistent Cookies</span></p>
            <p class="c4"><span class="c0">Administered by: Us</span></p>
            <p class="c1 c14">
                <span class="c0">
                    Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal
                    experience and to avoid You having to re-enter your preferences every time You use the Website.
                </span>
            </p>
            <p class="c1"><span class="c0">For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</span></p>
            <h2 class="c10"><span class="c6">Use of Your Personal Data</span></h2>
            <p class="c1"><span class="c0">The Company may use Personal Data for the following purposes:</span></p>
            <p class="c4"><span class="c5">To provide and maintain our Service</span><span class="c0">, including to monitor the usage of our Service.</span></p>
            <p class="c4">
                <span class="c5">To manage Your Account:</span>
                <span class="c0">&nbsp;to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</span>
            </p>
            <p class="c4">
                <span class="c5">For the performance of a contract:</span>
                <span class="c0">&nbsp;the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</span>
            </p>
            <p class="c4">
                <span class="c5">To contact You:</span>
                <span class="c0">
                    &nbsp;To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&#39;s push notifications regarding updates or informative communications related to the
                    functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
                </span>
            </p>
            <p class="c4">
                <span class="c5">To provide You</span>
                <span class="c0">
                    &nbsp;with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive
                    such information.
                </span>
            </p>
            <p class="c4"><span class="c5">To manage Your requests:</span><span class="c0">&nbsp;To attend and manage Your requests to Us.</span></p>
            <p class="c4">
                <span class="c5">For business transfers:</span>
                <span class="c0">
                    &nbsp;We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of
                    bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.
                </span>
            </p>
            <p class="c1 c14">
                <span class="c5">For other purposes</span>
                <span class="c0">
                    : We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services,
                    marketing and your experience.
                </span>
            </p>
            <p class="c1"><span class="c0">We may share Your personal information in the following situations:</span></p>
            <ul class="c3 lst-kix_list_1-0">
                <li class="c11 c8 li-bullet-0">
                    <span class="c5">With Service Providers:</span><span class="c0">&nbsp;We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</span>
                </li>
                <li class="c8 c11 li-bullet-0">
                    <span class="c5">For business transfers:</span>
                    <span class="c0">
                        &nbsp;We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another
                        company.
                    </span>
                </li>
                <li class="c11 c8 li-bullet-0">
                    <span class="c5">With Affiliates:</span>
                    <span class="c0">
                        &nbsp;We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture
                        partners or other companies that We control or that are under common control with Us.
                    </span>
                </li>
                <li class="c11 c8 li-bullet-0"><span class="c5">With business partners:</span><span class="c0">&nbsp;We may share Your information with Our business partners to offer You certain products, services or promotions.</span></li>
                <li class="c11 c8 li-bullet-0">
                    <span class="c5">With other users:</span>
                    <span class="c0">&nbsp;when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</span>
                </li>
                <li class="c1 c8 li-bullet-0"><span class="c5">With Your consent</span><span class="c0">: We may disclose Your personal information for any other purpose with Your consent.</span></li>
            </ul>
            <h2 class="c10"><span class="c6">Retention of Your Personal Data</span></h2>
            <p class="c1">
                <span class="c0">
                    The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal
                    obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                </span>
            </p>
            <p class="c1">
                <span class="c0">
                    The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality
                    of Our Service, or We are legally obligated to retain this data for longer time periods.
                </span>
            </p>
            <h2 class="c10"><span class="c6">Transfer of Your Personal Data</span></h2>
            <p class="c1">
                <span class="c0">
                    Your information, including Personal Data, is processed at the Company&#39;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be
                    transferred to &mdash; and maintained on &mdash; computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
                </span>
            </p>
            <p class="c1"><span class="c0">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</span></p>
            <p class="c1">
                <span class="c0">
                    The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a
                    country unless there are adequate controls in place including the security of Your data and other personal information.
                </span>
            </p>
            <h2 class="c10"><span class="c6">Delete Your Personal Data</span></h2>
            <p class="c1"><span class="c0">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</span></p>
            <p class="c1"><span class="c0">Our Service may give You the ability to delete certain information about You from within the Service.</span></p>
            <p class="c1">
                <span class="c0">
                    You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also
                    contact Us to request access to, correct, or delete any personal information that You have provided to Us.
                </span>
            </p>
            <p class="c1"><span class="c0">Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</span></p>
            <h2 class="c10"><span class="c6">Disclosure of Your Personal Data</span></h2>
            <h3 class="c10"><span class="c9">Business Transactions</span></h3>
            <p class="c1">
                <span class="c0">
                    If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
                </span>
            </p>
            <h3 class="c10"><span class="c9">Law enforcement</span></h3>
            <p class="c1">
                <span class="c0">
                    Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
                </span>
            </p>
            <h3 class="c10"><span class="c9">Other legal requirements</span></h3>
            <p class="c1"><span class="c0">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</span></p>
            <ul class="c3 lst-kix_list_1-0">
                <li class="c11 c8 li-bullet-0"><span class="c0">Comply with a legal obligation</span></li>
                <li class="c11 c8 li-bullet-0"><span class="c0">Protect and defend the rights or property of the Company</span></li>
                <li class="c11 c8 li-bullet-0"><span class="c0">Prevent or investigate possible wrongdoing in connection with the Service</span></li>
                <li class="c11 c8 li-bullet-0"><span class="c0">Protect the personal safety of Users of the Service or the public</span></li>
                <li class="c1 c8 li-bullet-0"><span class="c0">Protect against legal liability</span></li>
            </ul>
            <h2 class="c10"><span class="c6">Security of Your Personal Data</span></h2>
            <p class="c1">
                <span class="c0">
                    The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to
                    protect Your Personal Data, We cannot guarantee its absolute security.
                </span>
            </p>
            <p class="c2 title"><span class="c12">Children&#39;s Privacy</span></p>
            <p class="c1">
                <span class="c0">
                    Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has
                    provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information
                    from Our servers.
                </span>
            </p>
            <p class="c1">
                <span class="c0">
                    If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent&#39;s consent before We collect and use that information.
                </span>
            </p>
            <p class="c2 title"><span class="c12">Links to Other Websites</span></p>
            <p class="c1">
                <span class="c0">
                    Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&#39;s site. We strongly advise You to review the Privacy Policy of
                    every site You visit.
                </span>
            </p>
            <p class="c1"><span class="c0">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</span></p>
            <p class="c2 title"><span class="c12">Changes to this Privacy Policy</span></p>
            <p class="c1"><span class="c0">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</span></p>
            <p class="c1">
                <span class="c0">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</span>
            </p>
            <p class="c1"><span class="c0">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</span></p>
            <p class="c2 title"><span class="c12">Contact Us</span></p>
            <p class="c1"><span class="c0">If you have any questions about this Privacy Policy, You can contact us:</span></p>
            <ul class="c3 lst-kix_list_1-0">
                <li class="c1 c8 li-bullet-0"><span class="c0">By email: nursingwebpal@gmail.com</span></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection
@section('javascript')
@endsection